import Head from 'next/head';

import { useAuth } from '../lib/auth';
import styles from '../styles/Home.module.css';

export default function Home() {
  const auth = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello, next 2025 🎉</h1>
      <button onClick={() => auth.signinWithGithub()}>Sign with Github</button>
      {auth?.user && <button onClick={() => auth.signout()}>Sign out</button>}
      <pre>{JSON.stringify(auth?.user, null, 2)}</pre>
    </div>
  );
}
